NegasiQuanta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio_page.urls')),
    path('message/', include('msg.urls')),
    path('accounts/', include('accounts.urls'))
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

msg/urls.py
from . import views
from django.urls import path

app_name = 'msg'

urlpatterns = [
    path('', views.message_list, name='message_list'),
    path('message_create/', views.message_create, name="message_create"),
    path('comment_create/<int:message_id>/', views.comment_create, name="comment_create"),
]

portfolio_page/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='portfolio_page'
urlpatterns = [
    path('', views.index, name='homepage')
]

accounts/models.py
from django.db import models

# Create your models here.

msg/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Message(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, )
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} - {}".format(self.author, self.snipped_message())

    def snipped_message(self):
        if len(self.message) > 20 :
            return self.message[:20] + " ..."
        return self.message

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True,)
    comment = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, blank=True, null=True, related_name="comments")

    def __str__(self):
    	return "{} - {}".format(self.author, self.comment)

portfolio_page/models.py
from django.db import models

# Create your models here.

msg/forms.py
from . import models
from django import forms


class CreateMessageForm(forms.ModelForm):

    class Meta:
           model = models.Message
           fields=[
           "message"]
           

class CreateCommentForm(forms.ModelForm):
    
    class Meta:
        model = models.Comment
        fields =[
        "comment",]

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
	if request.method == "POST":
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user=form.save()
			login(request, user)
			# log the user in (cont.)
			return redirect('msg:message_list')
	else:
		form = UserCreationForm()
	return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
	if request.method =="POST":
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user=form.get_user()
			login(request,user)
			return redirect('msg:message_list')
	        # log the user in (cont.)
	else:
		form = AuthenticationForm()
	return render(request, 'accounts/login.html', {'form':form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('msg:message_list')

msg/views.py
from django.shortcuts import render, redirect
from .models import Message, Comment
from .import forms
from django.contrib.auth.decorators import login_required


# Create your views here.


def message_list(request):
    messages = Message.objects.all()
    message_form = forms.CreateMessageForm()
    comment_form = forms.CreateCommentForm()
    response = {
        'msgs' : messages,
        'form' : message_form,
        'comment_form' : comment_form
    }
    return render(request, 'msg/message_list.html', response)

@login_required(login_url="/accounts/login")
def message_create(request):
    message_form = forms.CreateMessageForm(request.POST)
    if request.method == "POST" and message_form.is_valid():
        instance=message_form.save(commit=False)
        instance.author =request.user
        instance.save()
        # Message.objects.create(
        #     message = message_form.cleaned_data['message'],
        # )
    return redirect('msg:message_list')

def comment_create(request, message_id):
    comment_form = forms.CreateCommentForm(request.POST)
    message=Message.objects.get(pk=message_id)
    if request.method == "POST" and comment_form.is_valid():
            instance=comment_form.save(commit=False)
            instance.author =request.user
            instance.message=message
            instance.save()
    return redirect('msg:message_list')

portfolio_page/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'portfolio_page/index.html')

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Sign Up</title>

</head>
<body>
    <h1>Log In</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{ form  }}
        <input type="submit" value="Log In">
    </form>
</body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html>
<head>
	<title>Sign Up</title>

</head>
<body>
	    <h1>Sign Up</h1>
    <form class="site-form" action="/accounts/signup/" method="POST">
    	{% csrf_token %}
        {{ form  }}
        <input type="submit" value="Sign Up">
    </form>


</body>
</html>

msg/templates/msg/message_list.html
{% load static from staticfiles %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'msg/Main.css' %}" >
    </head>
    <body>

                    
              

        <form action="{% url 'msg:message_create' %}" method="POST">
            {% csrf_token %}
            <div>
                {% for field in form.visible_fields %}
                    {{ field }}
                {% endfor %}
            </div>
            <button type="submit">Add!</button>
        </form>
        <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit">Log Out</button>
        </form>

        {% for message in msgs %}
            <h6>{{ message.author.username }}</h6>
            <p>{{ message.message }}</p>
            <p>{{ message.created_at }}</p>
            <form method="POST" action="{% url 'msg:comment_create' message_id=message.id %}">
                    {% csrf_token %}
                <div>
                        {% for field in comment_form.visible_fields %}
                        {{ field }}
                    {% endfor %}
                    <button type="submit">Komen Netijen!</button>
                </div>
                  
                
            </form>
            {% for comment in message.comments.all %}
                    <div>
                    {{ comment.comment }} by {{ comment.author.username }}
                </div>
            {% endfor %}
        {% endfor %}
    </body>
</html>

portfolio_page/templates/portfolio_page/index.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>My Profile</title>
        <link href="{% static 'portfolio_page/Main.css' %}" rel="stylesheet">

    </head>

    <body>
        <!-- header start -->
        <div id="header" class="section">
            <p>Kefas Satrio Bangkit Solideantyo</p>
            <img alt="Cool shit" class="img-circle" src="{% static 'portfolio_page/images/walrus Sharinggan .jpg' %}" style="height:50%;width:50%;margin-top:10px">
        </div>
        <!-- header end -->

        <!-- About Me section start -->
        <div class="section">
            <h1><span>About Me</span></h1>
            <p>
                Hey! I'm <strong>Kefas</strong>. I've never really learned HTML and CSS properly, since I've been too busy studying DDP1 and Discrete Mathematics. This is my first time using coding with HTML and CSS. By <i>coding</i> I mean <b>copy-pasting</b>  codes from <a href="http://www.sololearn.com"> <ins>SoloLearn</ins> </a>.
                <br>
                So....
                <br>
                Yeah...
                <br>
                I don't really understand what <strong>ALL</strong> of these codes do, but I do understand <i>some</i> parts of them.
                <br>
                Like, I understand the basics on how to add and edit the text and images, so at least I get to learn a little, <i>even though I copy-pasted</i>.
            </p>
            <p class="quote">"I love anime" - Elon Musk</p>
        </div>
        <!-- About Me section end -->

        <!-- My Schedule section start -->
        <div class="section">
            <h1><span>My Achievements</span></h1>
            <ul>
                <li><b><i>Cooked a 3-minute instant cup noodles in under 2 minutes</i></b></li>
                <p class="popmie"><img src ="http://assets.klikindomaret.com/products/10000975/10000975_1.jpg" style="width:30%;heigt:30%;"></p>
                <li><b><i>Beauty Make Up contest (1st place winner)</i></b></li>
                <p class="makeup"><img src="{% static 'portfolio_page/images/before after.jpg' %}" style="width:80%;height:80%;"></p>
                <li><b><i>Bergulat dengan Godzilla</i></b></li>
                <p class="godzilla"><img src="{% static 'portfolio_page/images/zilla vs epas.jpg' %}" style="width:80%;height:80%;"></p>

            </ul>


        </div>
        <!-- My Schedule section end -->


        <!-- My Skills section start -->
        <div class="section">
            <h1><span>My Skills</span></h1>
            <ul>
                </li>
                <li>Microsoft Office <br>
                    <progress min="0" max="100" value="75"></progress>
                </li>
                <li>Photoshop <br />
                    <progress min = "0" max="100" value="55"></progress>
                </li>
                <li>Python <br />
                    <progress min="0" max="100" value="40"></progress>
                </li>
                <li>HTML <br />
                    <progress min="0" max="100" value="10"></progress>
                </li>
                <li>Copy-pasting skills<br>
                    <progress min="0" max="100" value="100"></progress>

            </ul>
        </div>
        <!-- My Skills section end -->
        <!-- FAQ -->
        <div class="section">
            <h1><span>F.A.Q</span></h1>
            <ul>
                <li>Kefas, Kefas apa yang bikin adem?<br>
                     <img src="https://www.static-src.com/wcsstore/Indraprastha/images/catalog/medium//93/MTA-1643457/cosmos_cosmos-16sdb-stand-fan--16-inch-_full02.jpg" style="height:45%; width:45%;">
                    <p><i>Kefas angin</i></p>
                </li>
                <br>
                <li>Kefas, Kefas apa yang lembut?<br>
                    <img src= "https://img.okeinfo.net/content/2015/04/13/194/1133181/intip-manfaat-bola-kapas-bagi-kecantikan-yIPtVeEtHS.jpg" style="height: 40%; weight: 40%;">
                    <p> <i>Kepas</i> </p>
                </li>

            </ul>
        </div>

         <!-- Media section start -->
        <div class="section">
            <h1><span>My Sponsors</span></h1>
            <h4 align="center"> Nutrisari </h4>
            <iframe height="350px" width="60%"align="center" src="https://www.youtube.com/embed/c1HhkGcC0OA" allowfullscreen></iframe>
            <h4 align="center"> Mecin </h4>
            <iframe height="350px" width="60%"align="center" src="https://www.youtube.com/embed/At2_qCUZrCw" allowfullscreen></iframe>
            <h4 align="center"> Tolak Angin </h4>
            <iframe height="350px" width="60%"align="center" src="https://www.youtube.com/embed/PEO7nq20VZw" allowfullscreen></iframe>


        </div>
        <!-- Media section end -->


        <!-- Contacts section start -->
        <div class="section" id="contacts">
            <h1><span>Follow Me!</span></h1>
            <div>
                <a href="https://www.facebook.com/profile.php?id=100010642963869" target="_blank">
                    <img style="height:5%; width:5%;" alt="Facebook" src="https://en.facebookbrand.com/wp-content/uploads/2016/05/flogo_rgb_hex-brc-site-250.png" />
                </a>
                <a href="https://www.instagram.com/kefas_satrio/?hl=en" target = "_blank">
                    <img style="height:7%; width:7%;" alt="Instagram" src="https://www.brandchannel.com/wp-content/uploads/2016/05/instagram-new-logo-may-2016.jpg"/>
                </a>
                <a href="https://twitter.com/kefas_satrio" target = "_blank">
                    <img style="height:6%; width:6%;" alt="Twitter" src="https://www.sololearn.com/Uploads/icons/twitter.png" />
                </a>
            </div>
        </div>
        <!-- Contacts section end -->

        <div class="section" >
            <p align="center"><img style="height:70%; width:70%;" alt="Thank You" src="{% static 'portfolio_page/images/thank you.jpg' %}" /></p>
        </div>

    </body>
</html>